Repository FC7-FE/fc7-homework, pull requests merged in 2022-05, with the labels that each got.

#11 [6주차 실습] 뉴스API를 이용하여 검색하고 결과 보여주기
  week6/woo-suk/news/css/main.css
  week6/woo-suk/news/css/variables.css
  week6/woo-suk/news/index.html
  week6/woo-suk/news/js/main.js
Labels: Type: Feature/Function

#10 feat: I created recent-news-search-app with vanila JS
  week6/jung-hoo/index.html
  week6/jung-hoo/main.js
  week6/jung-hoo/style.css
Labels: Status: Request, Type: Feature/Function

#9 feat: create newsapi toyproject
  .gitignore
  week6/hun-geun/newsapi/.vscode/settings.json
  week6/hun-geun/newsapi/images/noimage.webp
  week6/hun-geun/newsapi/index.html
  week6/hun-geun/newsapi/main.css
  week6/hun-geun/newsapi/main.js
Labels: Status: Request, Type: Feature/Function

#18 Hun geun
  .gitignore
  week6/hun-geun/newsapi/.vscode/settings.json
  week6/hun-geun/newsapi/images/noimage.webp
  week6/hun-geun/newsapi/index.html
  week6/hun-geun/newsapi/main.css
  week6/hun-geun/newsapi/main.js
Labels: Status: Merge, Type: Feature/Function
